version: '3'
services:
  eventstore:
    build: .
    ports:
    - "8000:8000"
    volumes:
    - logvolume01:/var/log
    environment:
      MONGODB_HOST: database
    links:
    - database
  database:
    image: mongo:4.0.8
    ports:
    - "27017:27017"
volumes:
  logvolume01: {}